import numpy as np
arr=np.ones(5)
print(arr,"\n")
arr2=np.ones((2,3))
print(arr2,"\n")
ones_int_array = np.ones(4, dtype=int)
print(ones_int_array,"\n")
ones_array_3d = np.ones((2, 3, 4))
print(ones_array_3d,"\n")
arr3=np.linspace(0,1,num=10)
print(arr3)
array_without_endpoint=np.linspace(0,1,endpoint=False)
print(array_without_endpoint)
array_2d=np.linspace(0,1,num=25).reshape(5,5)
print(array_2d)
