import numpy
x=numpy.array([[1,2],[4,5]])
y=numpy.array([[7,8],[9,10]])
print(x)
print(y)
print("element wise addition :")
print(numpy.add(x,y))
print("element wise subtraction :")
print(numpy.subtract(x,y))
print("element wise division of matrix is :")
print(numpy.divide(x,y))
print("element wise multiplication : ")
print(numpy.multiply(x,y))
print("the product of matrice is : ")
print(numpy.dot(x,y))
print("the sqrt of each element in a matrix :")
print("sqrt of a ",numpy.sqrt(x))
print("the sum of all elements in axis=0:")
print(numpy.sum(y,axis=0))
print("the sum of all elements in axis=1:")
print(numpy.sum(y,axis=1))
print("the transpose of given matrix is ")
print(x.T)
