import numpy as np
arr=np.array([1,2,3,4,5])
values=[np.array([6,7]),np.array([8,9])]
new_arr=np.append(arr,values)
print(new_arr)
arr=np.arange(1,13).reshape(2,6)
print("original array : ")
print(arr,"\n")
col=np.arange(5,11).reshape(1,6)
print("to be appended : ")
print(col,"\n")
apd=np.append(arr,col,axis=0)
print(apd)
print("without any axis ")
apd=np.append(arr,col)
print(apd)
row=np.array([1,2]).reshape(2,1)
print("array to be reshaped row wise:")
print(row)
arr_row=np.append(arr,row,axis=1)
print("axis=1:")
print(arr_row)
