import pandas as pd
df1=pd.read_excel("sample_stock_data.xlsx")
print(df1)
df2=pd.read_excel("sample_stock_data.xlsx",sheet_name="Usa")
print(df2)
df3=pd.read_excel("sample_stock_data.xlsx",usecols=[0,3])
print(df3)
df4=pd.read_excel("sample_stock_data.xlsx",sheet_name="Usa",usecols=[0,3])
print(df4)
df5=pd.read_excel("sample_stock_data.xlsx",na_values="Missing")
df6=pd.read_excel("sample_stock_data.xlsx",sheet_name="Usa",skiprows=[2,4,7])
print(df6)
df7=pd.read_excel("sample_stock_data.xlsx",sheet_name=["India","Usa"],header=2)
print(df7)
df8=pd.read_excel("sample_stock_data.xlsx",sheet_name=None,skiprows=[2,3,4,5])
print(df8)
